# Controller-specific settings
cloudtrail:
  serviceAccount:
    name: ack-cloudtrail-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.cloudtrail}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

cloudwatchlogs:
  serviceAccount:
    name: ack-cloudwatchlogs-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.cloudwatchlogs}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

ec2:
  serviceAccount:
    name: ack-ec2-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.ec2}}"
  resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

efs:
  serviceAccount:
    name: ack-efs-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.efs}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

eks:
  serviceAccount:
    name: ack-eks-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.eks}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

iam:
  serviceAccount:
    name: ack-iam-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.iam}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

kms:
  serviceAccount:
    name: ack-kms-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.kms}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

opensearchservice:
  serviceAccount:
    name: ack-opensearchservice-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.opensearchservice}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

rds:
  serviceAccount:
    name: ack-rds-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.rds}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

route53:
  serviceAccount:
    name: ack-route53-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.route53}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

s3:
  serviceAccount:
    name: ack-s3-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.s3}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

secretsmanager:
  serviceAccount:
    name: ack-secretsmanager-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.secretsmanager}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

sns:
  serviceAccount:
    name: ack-sns-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.sns}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

sqs:
  serviceAccount:
    name: ack-sqs-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.sqs}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

wafv2:
  serviceAccount:
    name: ack-wafv2-sa
    annotations:
      eks.amazonaws.com/role-arn: "{{.Values.global.roleArns.wafv2}}"
  aws:
    region: "{{.Values.global.aws_region}}"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
# End of controller-specific settings
