# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# # GCP Gen3 ResourceGraphDefinitions
# resources:
#   - cloudsql-rgd.yaml
#   - gke-rgd.yaml
#   - storage-bucket-rgd.yaml
#   - vpc-rgd.yaml
