apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

resources:
  - adoptedresources.services.k8s.aws.yaml
  - fieldexports.services.k8s.aws.yaml
  - healthchecks.route53.services.k8s.aws.yaml
  - hostedzones.route53.services.k8s.aws.yaml
  - recordsets.route53.services.k8s.aws.yaml
