apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Gen3 Infrastructure Stack (Layer-2)
# Composite RGD requiring: ack-ec2, ack-s3, ack-rds, ack-eks, ack-iam

resources:
  - gen3-infrastructure-rgd.yaml
  - generic-commons-bucket-rgd.yaml
