apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - adoptedresources.services.k8s.aws.yaml
  - eventdatastores.cloudtrail.services.k8s.aws.yaml
  - fieldexports.services.k8s.aws.yaml
  - trails.cloudtrail.services.k8s.aws.yaml
