apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - adoptedresources.services.k8s.aws.yaml
  - fieldexports.services.k8s.aws.yaml
  - secrets.secretsmanager.services.k8s.aws.yaml
