apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure # Infrastructure instance
  - cluster-addons # Cluster addons
  - sample.gen3.url.org # App instance 1 (more can be added)


patches:
  - target:
      group: kro.run
    patch: |-
      - op: replace
        path: /spec/namespace
        value: spoke1
  - target:
      group: kro.run
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: spoke1
