apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # App instance 1
  - sample.gen3.url.org

patches:
  - target:
      group: kro.run
    patch: |-
      - op: replace
        path: /spec/namespace
        value: spoke1
  - target:
      group: kro.run
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: spoke1
