apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bootstrap
  namespace: argocd-ns
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false # to be able to cleanup
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: bootstrap
    spec:
      project: default
      source:
        repoURL: '{{.metadata.annotations.csoc_repo_url}}'
        path: '{{.metadata.annotations.bootstrap_path}}'
        targetRevision: '{{.metadata.annotations.csoc_repo_revision}}'
        directory:
          recurse: true
          exclude: exclude/*
      destination:
        namespace: 'argocd-ns'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
