apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

resources:
  - adoptedresources.services.k8s.aws.yaml
  - aliases.kms.services.k8s.aws.yaml
  - fieldexports.services.k8s.aws.yaml
  - grants.kms.services.k8s.aws.yaml
  - keys.kms.services.k8s.aws.yaml
