apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../instance-templates/aws/namespace.yaml
  - ../../../instance-templates/aws/vpc-instance.yaml

configMapGenerator:
  - name: spoke-values
    envs: [../_flavor_defaults/gen3-aws-dev.env]
    options:
      disableNameSuffixHash: true

labels:
  - pairs: {flavor: gen3-aws-dev, environment: development, app.kubernetes.io/managed-by: kustomize}

commonAnnotations: {managed-by: kro, flavor: gen3-aws-dev}
