apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

resources:
  - adoptedresources.services.k8s.aws.yaml
  - fieldexports.services.k8s.aws.yaml
  - groups.iam.services.k8s.aws.yaml
  - instanceprofiles.iam.services.k8s.aws.yaml
  - openidconnectproviders.iam.services.k8s.aws.yaml
  - policies.iam.services.k8s.aws.yaml
  - roles.iam.services.k8s.aws.yaml
  - servicelinkedroles.iam.services.k8s.aws.yaml
  - users.iam.services.k8s.aws.yaml
