apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization

resources:
  - adoptedresources.services.k8s.aws.yaml
  - cacheclusters.elasticache.services.k8s.aws.yaml
  - cacheparametergroups.elasticache.services.k8s.aws.yaml
  - cachesubnetgroups.elasticache.services.k8s.aws.yaml
  - fieldexports.services.k8s.aws.yaml
  - replicationgroups.elasticache.services.k8s.aws.yaml
  - serverlesscaches.elasticache.services.k8s.aws.yaml
  - serverlesscachesnapshots.elasticache.services.k8s.aws.yaml
  - snapshots.elasticache.services.k8s.aws.yaml
  - usergroups.elasticache.services.k8s.aws.yaml
  - users.elasticache.services.k8s.aws.yaml
