apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# ConfigMapGenerator to create spokes-charter ConfigMap
configMapGenerator:
  - name: spokes-charter
    files:
      - spokes-charter.yaml=../spokes-charter.yaml
    options:
      labels:
        app.kubernetes.io/name: spokes-charter
        app.kubernetes.io/part-of: gen3-kro
        app.kubernetes.io/managed-by: kustomize

# Resources to deploy
resources:
  - namespace-template.yaml

# Replacements/patches will be done by ArgoCD ApplicationSet templating
