apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base AWS infrastructure instances
# These serve as templates for spoke-specific overlays

resources:
  - namespace.yaml
  - vpc-instance.yaml
  - aurora-instance.yaml
  - cloudtrail-instance.yaml
  - cloudwatch-logs-instance.yaml
  - data-bucket-instance.yaml
  - efs-instance.yaml
  - eks-instance.yaml
  - elasticache-instance.yaml
  - irsa-role-instance.yaml
  - kms-instance.yaml
  - opensearch-instance.yaml
  - rds-instance.yaml
  - route53-instance.yaml
  - secretsmanager-instance.yaml
  - sns-instance.yaml
  - sqs-instance.yaml
  - waf-instance.yaml
