apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - adoptedresources.services.k8s.aws.yaml
  - dbclusterendpoints.rds.services.k8s.aws.yaml
  - dbclusterparametergroups.rds.services.k8s.aws.yaml
  - dbclustersnapshots.rds.services.k8s.aws.yaml
  - dbclusters.rds.services.k8s.aws.yaml
  - dbinstances.rds.services.k8s.aws.yaml
  - dbparametergroups.rds.services.k8s.aws.yaml
  - dbproxies.rds.services.k8s.aws.yaml
  - dbsnapshots.rds.services.k8s.aws.yaml
  - dbsubnetgroups.rds.services.k8s.aws.yaml
  - fieldexports.services.k8s.aws.yaml
  - globalclusters.rds.services.k8s.aws.yaml
